version: '2'
services:
  web:
    build: .
    command: npm run serve-dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3001:3001"