version: '2'
services:
  itransfer-backend:
    build: .
    command: npm run serve-dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3001:3001"
      - "3002:3002"
    links:
      - itransfer-mysql
    depends_on:
      - itransfer-mysql
  itransfer-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - dbinfo:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: itransfer


volumes:
  dbinfo:
